# Bindings for MBP 2019
# MBP: Screen Brightness
unbind = , XF86MonBrightnessUp
unbind = , XF86MonBrightnessDown

bind = , XF86MonBrightnessUp, exec, brightnessctl -d gmux_backlight set +10% && omarchy-swayosd-brightness "$(brightnessctl -d gmux_backlight -m | cut -d',' -f4 | tr -d '%')"
bind = , XF86MonBrightnessDown, exec, brightnessctl -d gmux_backlight set 10%- && omarchy-swayosd-brightness "$(brightnessctl -d gmux_backlight -m | cut -d',' -f4 | tr -d '%')"

# MBP: Keyboard LED Brightness
unbind = , XF86KbdBrightnessUp
unbind = , XF86KbdBrightnessDown

bind = , XF86KbdBrightnessUp, exec, brightnessctl -d :white:kbd_backlight set +20% && omarchy-swayosd-kbd-brightness $(( $(brightnessctl -d ':white:kbd_backlight' get) * 100 / $(brightnessctl -d ':white:kbd_backlight' max) ))
bind = , XF86KbdBrightnessDown, exec, brightnessctl -d :white:kbd_backlight set 20%- && omarchy-swayosd-kbd-brightness $(( $(brightnessctl -d ':white:kbd_backlight' get) * 100 / $(brightnessctl -d ':white:kbd_backlight' max) ))

# MBP: Touchbar Brightness
bind = SHIFT, XF86KbdBrightnessUp, exec, brightnessctl -d appletb_backlight set 1+ && omarchy-swayosd-kbd-brightness $(( $(brightnessctl -d 'appletb_backlight' get) * 100 / $(brightnessctl -d 'appletb_backlight' max) ))
bind = SHIFT, XF86KbdBrightnessDown, exec, brightnessctl -d appletb_backlight set 1- && omarchy-swayosd-kbd-brightness $(( $(brightnessctl -d 'appletb_backlight' get) * 100 / $(brightnessctl -d 'appletb_backlight' max) ))

# MBP: unused mic button to toggle mute, could not find icon to change or display like volume/brightness function so used a notification
unbind = , XF86AudioMicMute
bind = , XF86AudioMicMute, exec, ~/bin/mbp-tb-mic-toggle

# MBP: unused search button to open menu 
bind = , XF86Search, exec, omarchy-menu

# MBP: Lid close suspend
bindl = , switch:on:Lid Switch, exec, systemctl suspend

