add_newline = true
command_timeout = 1000

format = """
$directory$git_branch$git_status$kubernetes
$character"""

right_format = "$cmd_duration$python$username$hostname"

[directory]
style = "blue"
truncate_to_repo = false
truncation_length = 3
format = "[$path]($style) "

[git_branch]
style = "bright-black"
symbol = ""
format = "[$branch]($style)"

[git_status]
style = "bright-black"
format = "[$all_status$ahead_behind]($style) "
modified = "*"
staged = "*"
untracked = "*"
ahead = ":⇡"
behind = ":⇣"
diverged = ":⇣⇡"

[kubernetes]
disabled = false
style = "cyan"
symbol = "⎈ "
format = "[$symbol$context(:$namespace)]($style) "
detect_files = ["Dockerfile","skaffold.yaml"]

[cmd_duration]
min_time = 5000
style = "yellow"
format = "[$duration]($style) "

[python]
style = "bright-black"
format = '[${virtualenv}]($style) '
detect_extensions = []
detect_files = []
detect_folders = []

[username]
style_user = "bright-black"
style_root = "white"
format = "[$user]($style)"

[hostname]
ssh_only = true
style = "bright-black"
format = "[@$hostname]($style) "

[character]
success_symbol = "[❯](magenta)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](magenta)"
vimcmd_replace_one_symbol = "[❮](magenta)"
vimcmd_replace_symbol = "[❮](magenta)"
vimcmd_visual_symbol = "[❮](magenta)"
