# Hyprland Overrides
# Autostart applications
exec-once = mega-sync
exec-once = Telegram -startintray
exec-once = omarchy-launch-browser
exec-once = [workspace 1] uwsm-app -- xdg-terminal-exec
exec-once = [workspace 1] sleep 2 && uwsm-app -- xdg-terminal-exec

# Enviornment variables
env = STOW_DIR, /home/gene/dotfiles/
env = PATH, /home/gene/bin:$PATH

# Monitor setup
env = GDK_SCALE,1
monitor=,preferred,auto,1

# Smart windows, single windows no gap and border
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = border_size 0, match:float 0, match:workspace w[tv1]
windowrule = rounding 0, match:float 0, match:workspace w[tv1]
windowrule = border_size 0, match:float 0, match:workspace f[1]
windowrule = rounding 0, match:float 0, match:workspace f[1]

# Set applications to specific workspace
# Get classes: hyprctl clients | grep class
# workspace 1

# workspace 2
windowrule = workspace 2, match:class org.telegram.desktop

# workspace 3
windowrule = workspace 3, float on, match:class Bitwarden

# workspace 4
windowrule = workspace 4, match:class code

# workspace 5
windowrule = workspace 5, match:class brave-browser
windowrule = workspace 5, match:class Thorium-browser

# workspace 6
windowrule = workspace 6 silent, match:class chromium

