# MBA: Keyboard LED Brightness
$keysswayosd = $osdclient --custom-progress=$(awk "BEGIN {print $(brightnessctl --device=smc::kbd_backlight get)/255}") --custom-icon=input-keyboard
bindeld = ,XF86KbdBrightnessDown, Keyboard Brightness down, exec, brightnessctl --device=smc::kbd_backlight set 10%- && $keysswayosd
bindeld = ,XF86KbdBrightnessUp, Keyboard Brightness up, exec, brightnessctl --device=smc::kbd_backlight set +10% && $keysswayosd
bindeld = SHIFT, XF86KbdBrightnessDown, Keyboard Brightness max, exec, brightnessctl --device=smc::kbd_backlight set 0% && $keysswayosd
bindeld = SHIFT, XF86KbdBrightnessUp, Keyboard Brightness max, exec, brightnessctl --device=smc::kbd_backlight set 100% && $keysswayosd
bindeld = ALT, XF86KbdBrightnessDown, Keyboard Brightness down precise, exec, brightnessctl --device=smc::kbd_backlight set 1%- && $keysswayosd
bindeld = ALT, XF86KbdBrightnessUp, Keyboard Brightness up precise, exec, brightnessctl --device=smc::kbd_backlight set +1% && $keysswayosd

